FROM payara/server-full:5.2021.4

# Imixs-JSF-Sample Version 1.0.2
MAINTAINER ralph.soika@imixs.com

# Setup configuration
USER payara
COPY ./docker/configuration/payara/postgresql-9.4.1212.jar /opt/payara/appserver/glassfish/domains/domain1/lib
COPY ./docker/configuration/payara/domain.xml /opt/payara/appserver/glassfish/domains/domain1/config
COPY ./docker/configuration/payara/keyfile /opt/payara/appserver/glassfish/domains/domain1/config 

USER root
RUN chown payara:payara /opt/payara/appserver/glassfish/domains/domain1/config/keyfile
USER payara

# ENV PAYARA_ARGS --debug
# Copy sample application
COPY ./target/imixs-jsf-example.war $DEPLOY_DIR