FROM tomee:11-jre-8.0.0-M3-plume
#FROM tomee:8-jre-8.0.0-M2-plume
#FROM tomee:8-jre-8.0.0-M2-microprofile

# Plume profile comes with EclipseLink and Eclipse Microprofile

# Imixs-JSF-Sample Version 1.0.2
MAINTAINER ralph.soika@imixs.com

# Copy postgres JDBC driver
#COPY ./src/docker/configuration/tomee/eclipselink.jar /usr/local/tomee/lib
COPY ./src/docker/configuration/tomee/postgresql-9.4.1212.jar /usr/local/tomee/lib

# Add config
COPY ./src/docker/configuration/tomee/server.xml /usr/local/tomee/conf
COPY ./src/docker/configuration/tomee/tomee.xml /usr/local/tomee/conf
COPY ./src/docker/configuration/tomee/tomcat-users.xml /usr/local/tomee/conf


# Copy sample application
COPY ./target/imixs-jsf-example.war /usr/local/tomee/webapps/
