version: "3.6"
services:

# Apache Solr example

  imixssample-db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: workflow-db
  
  imixssample-app:
    image: imixs/imixs-jsf-example
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://imixssample-db/workflow-db"
    ports:
      - "8080:8080"
      - "8787:8787"
      - "9990:9990"
    volumes:
      - ./docker/deployments:/opt/wildfly/standalone/deployments/    

  solr:
    image: solr:8.2
    ports:
      - "8983:8983"      
      
    volumes:
      - solr-data:/opt/solr/server/solr/imixs-workflow
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - imixs-workflow


  imixsadmin:
    image: imixs/imixs-admin
    ports:
      - "8888:8080"    
      
      
volumes:
  solr-data: 