version: "3.1"
services:

  imixssample-db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: workflow-db
  
  imixssample-app:
    image: imixs/imixs-jsf-example
    environment:
      WILDFLY_PASS: adminadmin
      DEBUG: "true"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "adminadmin"
      POSTGRES_CONNECTION: "jdbc:postgresql://imixssample-db/workflow-db"
    ports:
      - "8080:8080"
      - "8787:8787"
      - "9990:9990"
    volumes:
      - ~/git/imixs-jsf-example/src/docker/deployments:/opt/wildfly/standalone/deployments/    
