version: "3.6"
services:

  imixssample-db:
    image: postgres:9.6.1
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: workflow-db
  
  imixssample-app:
    depends_on:
      - imixssample-db
    image: imixs/imixs-jsf-example
    depends_on:
      - imixssample-db
    environment:
      MODEL_DEFAULT_DATA: "ticket.bpmn"
      TZ: "Europe/Berlin"
    ports:
      - "8080:8080"
      - "8009:8009"
      - "8888:8888"
#    volumes:
#      - ./docker/deployments:/config/dropins/   



    
#  imixsadmin:
#    image: imixs/imixs-admin
#    ports:
#      - "8888:8080"